### ISSUE TITLE
デプロイ用のPRをActionsで自動作成できるようにする。

### ISSUE THREAD

**Issue by riscait** [altive/flutter_app_template#226]
- [ci/cd: GitHub Appで生成されたトークンで認証してリリース用PRを作成する形に修正 #804
](https://github.com/Favosia/favosia_flutter/pull/804)
- https://github.com/Favosia/favosia_flutter/pull/809

**Comment by naipaka** [comment]
@riscait 
こちらCloseできそうですかね！🚀

**Comment by riscait** [comment]
ありがとうございます！こちらCloseですね🙌
